### ISSUE TITLE
How to create my MOTS dataset just like APOLLO MOTS?

### ISSUE THREAD

**Issue by FinalFlowers** [detectRecog/PointTrack#1]

**Comment by detectRecog** [comment]
If you have downloaded KITTI MOTS, you will find it is easy to do so in three steps.

1. put all images to a folder named 'images'.
2. put all corresponding PNG instance annotations (each instance has a unique ID) to a folder named 'instances'.
3.create the '.segmap' which represents the train/val/test split. Please refer to [mots_tools](https://github.com/VisualComputingInstitute/mots_tools)

**Comment by FinalFlowers** [comment]
Thank you!
