### ISSUE TITLE
What is your platform for testing time of network.

### ISSUE THREAD

**Issue by BlueCat7** [detectRecog/PointTrack#10]
Dear Author, I test time on V100, but the speed of network is different from yours. Could you please offer some details about how you test model speed.

**Comment by detectRecog** [comment]
I think the reason is that we implement the post-processing in C++ in the test time. The python post-processing provided in this repo is very slow. As the C++ version is used in commercial production, we do not provide it.

**Comment by BlueCat7** [comment]
Ok, thanks your replay. I will check again.
