### ISSUE TITLE
How to visualize the MOTS results

### ISSUE THREAD

**Issue by EchoAmor** [detectRecog/PointTrack#12]
Thanks for your great work! It's really helpful! But after I got the tracking results ,I didn't find the visualization.py , can  u publish the code ? Thanks a lot!

**Comment by EchoAmor** [comment]
@detectRecog  Hi, Is the visualization code in the **_datasets_**?

**Comment by Ilyabasharov** [comment]
@EchoAmor hello, the code for vis is located in datasets ([link](https://github.com/detectRecog/PointTrack/blob/master/datasets/mots_tools/mots_vis/visualize_mots.py)). so u should run this file with keys : txt folder - result of tracking, dir with images, dir where to save visualisation, additional file (.segmap) located in mots_eval.
example of run: 
!python visualize_mots.py dir/with/txt /root/pointTrack/data/kittiRoot/testing/image_02 results /root/pointTrack/datasets/mots_tools/mots_eval/test.seqmap

**Comment by EchoAmor** [comment]
@Ilyabasharov Thanks again, I have found that and got the results . 
BTW, can u please share how to train the model  on cars and pedestrians together? Now only got the car results, thanks a lot!

**Comment by Ilyabasharov** [comment]
@EchoAmor as I understood main problem is in spatial emb. it (posted code) supports only one class mb I am wrong. I solved it by train spatial emb on two classes but changed the annotation to one class. The second solution what I chose was to change spatial emb to other segmentation model witch can be faster

**Comment by EchoAmor** [comment]
@Ilyabasharov Thanks! I am working on spatial embeddding's code now ,  I thought about change other segmentation too, maybe later, thanks again!
