### ISSUE TITLE
How to calculate category_embedding for my own dataset?

### ISSUE THREAD

**Issue by ljjyxz123** [detectRecog/PointTrack#16]
In config.py, line 8, there is category_embedding definition: 
https://github.com/detectRecog/PointTrack/blob/master/config.py#L8
category_embedding = [[0.9479751586914062, 0.4561353325843811, 0.16707628965377808], [0.1,-0.1,0.1], [0.5455077290534973, -0.6193588972091675, -2.629554510116577], [-0.1,0.1,-0.1]]

How is this value calculated?
If I want to train my own dataset, how to calculate the category_embedding for my own category?

Thanks! @detectRecog

**Comment by MLbyML** [comment]
Hello @detectRecog , thank you for making your code public and for proving a very interesting approach to tracking. 
I have the same question as @ljjyxz123 above.
I noticed that `category_embedding` is provided as a global parameter accessed by the code, how should we interpret this 4 x 3 matrix?  Thanks for the help in advance!
