### ISSUE TITLE
Could I ask how to generate segmentation for KITTI test set?

### ISSUE THREAD

**Issue by fandulu** [detectRecog/PointTrack#4]
Could I ask how to generate segmentation for KITTI test set?

**Comment by detectRecog** [comment]
It needs minor modification 'datasets.KittiMOTSDataset.MOTSCarsVal' to let it load testset images.

**Comment by fandulu** [comment]
but  'datasets.KittiMOTSDataset.MOTSCarsVal' need to load the given masks, instead of predicting masks.

**Comment by detectRecog** [comment]
Hello, for the convenience of comparisons with PointTrack, we have provided the test set results of PointTrack on cars and pedestrians on the GitHub page.

**Comment by fandulu** [comment]
thanks
